"use client";
import { useMemo } from "react";
import * as THREE from "three";
import { MARS_VISUAL_SPEC as SPEC } from "./mars-visual-spec";

const P=SPEC.palette,L=SPEC.lighting;
const standard={roughness:.65,metalness:.3};
function Practical({position,type="violet"}:{position:[number,number,number];type?:"violet"|"white"}){const light=type==="white"?L.whitePractical:L.violetPractical;return <pointLight position={position} color={light.color} intensity={light.intensity} distance={light.distance} decay={light.decay}/>}

export function SignalArray(){const profile=useMemo(()=>Array.from({length:13},(_,i)=>{const r=3.75*i/12;return new THREE.Vector2(r,1.8*(r/3.75)**2)}),[]);return <group rotation={[0,SPEC.destinations.array.rotationY,0]}>
  <mesh position={[0,.6,0]} castShadow receiveShadow><cylinderGeometry args={[2.6,3.1,1.2,12]}/><meshStandardMaterial color={P.structureDark} {...standard}/></mesh><mesh position={[0,2.8,0]} castShadow><cylinderGeometry args={[.9,1.4,3.2,12]}/><meshStandardMaterial color={P.structureMid} {...standard}/></mesh>
  <group position={[0,5,0]} rotation={[-.72,0,.12]}><mesh castShadow><latheGeometry args={[profile,32]}/><meshStandardMaterial color={P.structureMid} side={THREE.DoubleSide} roughness={.58} metalness={.4}/></mesh><mesh position={[0,1.8,0]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[3.75,.08,8,40]}/><meshStandardMaterial color={P.structureLight} metalness={.45}/></mesh>{[0,Math.PI*2/3,Math.PI*4/3].map((a,i)=><mesh key={i} position={[Math.cos(a)*1.45,.48,Math.sin(a)*1.45]} rotation={[Math.sin(a)*-.28,0,Math.cos(a)*.28]}><cylinderGeometry args={[.055,.055,3.15,6]}/><meshStandardMaterial color={P.structureLight}/></mesh>)}<mesh position={[0,1.02,0]}><cylinderGeometry args={[.25,.34,.75,10]}/><meshStandardMaterial color={P.structureLight} {...standard}/></mesh></group>
  {[-2.05,0,2.05].map(x=><group key={x}><mesh position={[x,.22,1.75]}><sphereGeometry args={[.1,8,8]}/><meshBasicMaterial color={P.violetBright}/></mesh><Practical position={[x,.28,1.75]}/></group>)}
</group>}

function HabitatDome({position,radius}:{position:[number,number,number];radius:number}){return <group position={position}><mesh scale={[1,.55,1]} castShadow><sphereGeometry args={[radius,24,12,0,Math.PI*2,0,Math.PI/2]}/><meshStandardMaterial color={P.structureLight} roughness={.72} metalness={.18}/></mesh>{[-.65,0,.65].map(x=><mesh key={x} position={[x*radius,.42,-radius*.78]}><boxGeometry args={[.1,.55,.05]}/><meshStandardMaterial color={P.structureDark}/></mesh>)}</group>}
export function ResearchOutpost(){return <group><HabitatDome position={[-2.8,1.1,0]} radius={2.7}/><HabitatDome position={[2,.9,-1.3]} radius={2.25}/><HabitatDome position={[4.5,.7,.7]} radius={1.65}/>{[-4,-2.7,-1.4,1.3,2.5].map((x,i)=><mesh key={x} position={[x,1.1,i<3?-2.12:-3.02]}><boxGeometry args={[.5,.2,.05]}/><meshStandardMaterial color={P.textPrimary} emissive={P.blueLight} emissiveIntensity={.45}/></mesh>)}<mesh position={[-.15,.55,-.8]}><boxGeometry args={[1.2,1.1,1.5]}/><meshStandardMaterial color={P.structureDark} {...standard}/></mesh>{[0,1].map(i=><mesh key={i} position={[6.6+i*1.65,.65,-1]} rotation={[-.22,0,0]}><boxGeometry args={[1.5,.08,2.4]}/><meshStandardMaterial color="#151D35" metalness={.45} roughness={.5}/></mesh>)}{[-.6,0,.6].map(x=><mesh key={x} position={[7.43+x,.7,-1]}><boxGeometry args={[.02,.1,2.35]}/><meshBasicMaterial color={P.structureMid}/></mesh>)}<mesh position={[-.15,1.25,-1.58]}><boxGeometry args={[.45,.16,.05]}/><meshBasicMaterial color={P.textPrimary}/></mesh><Practical position={[-.15,1.35,-1.8]} type="white"/><mesh position={[5.5,.2,2]}><boxGeometry args={[1.2,.4,.8]}/><meshStandardMaterial color={P.structureMid}/></mesh></group>}

export function MissionArchive(){return <group><mesh position={[0,2.9,0]} castShadow><boxGeometry args={SPEC.destinations.archive.primary}/><meshStandardMaterial color={P.structureDark} roughness={.65} metalness={.35}/></mesh><mesh position={[3.1,1,1.4]} castShadow><boxGeometry args={SPEC.destinations.archive.secondary}/><meshStandardMaterial color={P.structureMid} roughness={.65} metalness={.35}/></mesh><mesh position={[0,.9,2.62]}><boxGeometry args={[1.5,1.8,.18]}/><meshStandardMaterial color="#080A11"/></mesh>{[-1.7,0,1.7].map(x=><mesh key={x} position={[x,3,2.63]}><boxGeometry args={[.28,4.1,.08]}/><meshStandardMaterial color="#080A11"/></mesh>)}<mesh position={[1.72,3,2.69]}><boxGeometry args={[.11,3.9,.04]}/><meshBasicMaterial color={P.violet}/></mesh><Practical position={[1.72,2.1,2.9]}/><mesh position={[-1.15,1.2,2.7]}><boxGeometry args={[.85,.42,.05]}/><meshBasicMaterial color={P.textPrimary}/></mesh><mesh position={[0,6.7,0]}><cylinderGeometry args={[.05,.08,1.8,8]}/><meshStandardMaterial color={P.structureLight}/></mesh></group>}

export function SystemsLab(){const columns:[number,number,number][]=[[-3,2.2,-2],[3,2.2,-2],[-3,2.2,2],[3,2.2,2]];return <group>{columns.map((p,i)=><mesh key={i} position={p} castShadow><boxGeometry args={[.32,4.4,.32]}/><meshStandardMaterial color={P.structureLight} {...standard}/></mesh>)}{[[-3,4.35,0],[3,4.35,0],[0,4.35,-2],[0,4.35,2]].map((p,i)=><mesh key={i} position={p as [number,number,number]}><boxGeometry args={i<2?[.3,.3,4.3]:[6.3,.3,.3]}/><meshStandardMaterial color={P.structureLight}/></mesh>)}<mesh position={[0,1,-1.55]}><boxGeometry args={[5.8,.25,1.4]}/><meshStandardMaterial color={P.structureMid}/></mesh><mesh position={[-1.7,1.7,-1.5]}><cylinderGeometry args={[.65,.65,1.4,12]}/><meshStandardMaterial color={P.structureMid}/></mesh><mesh position={[1.6,1.6,-1.5]}><boxGeometry args={[1.6,1.3,1.2]}/><meshStandardMaterial color={P.structureDark}/></mesh><group position={[0,2.25,.9]} rotation={[0,0,-.22]}><mesh><boxGeometry args={[3.4,.18,.18]}/><meshStandardMaterial color={P.roverSecondary}/></mesh><mesh position={[1.55,-.7,0]} rotation={[0,0,.5]}><boxGeometry args={[.18,1.6,.18]}/><meshStandardMaterial color={P.roverSecondary}/></mesh></group><mesh position={[2.4,5.1,-1.4]}><cylinderGeometry args={[.05,.08,2,7]}/><meshStandardMaterial color={P.structureLight}/></mesh><Practical position={[-2.5,3.7,0]} type="white"/><Practical position={[2.5,3.7,0]} type="white"/><pointLight position={[0,1.4,-1]} color={P.violet} intensity={.7} distance={6} decay={2}/></group>}

export function FieldLog(){return <group><mesh position={[0,.65,0]}><boxGeometry args={[2,1.3,1.6]}/><meshStandardMaterial color={P.structureDark} {...standard}/></mesh><mesh position={[0,1.5,-.45]} rotation={[-.35,0,0]}><boxGeometry args={[1.5,.15,.9]}/><meshStandardMaterial color={P.structureLight}/></mesh><mesh position={[.65,2.5,.3]}><cylinderGeometry args={[.05,.08,3.1,7]}/><meshStandardMaterial color={P.roverSecondary}/></mesh><mesh position={[.65,4.05,.3]}><sphereGeometry args={[.14,8,8]}/><meshBasicMaterial color={P.violetBright}/></mesh><mesh position={[-1.35,.35,.5]}><boxGeometry args={[.8,.7,.7]}/><meshStandardMaterial color={P.structureMid}/></mesh><Practical position={[.65,3.8,.3]}/></group>}
export function TrajectoryWaypoint(){return <group><mesh position={[0,.35,0]}><cylinderGeometry args={[.7,.9,.7,8]}/><meshStandardMaterial color={P.structureDark}/></mesh>{[[1.4,.12,1.5],[3,.09,1.5],[4.45,.06,1.2]].map(([y,r,h],i)=><mesh key={i} position={[0,y,0]}><cylinderGeometry args={[r,r,h,7]}/><meshStandardMaterial color={i===1?P.structureLight:P.structureMid}/></mesh>)}<mesh position={[0,5.15,0]}><octahedronGeometry args={[.3]}/><meshStandardMaterial color={P.violetBright} emissive={P.violet} emissiveIntensity={.85}/></mesh><Practical position={[0,5.1,0]}/></group>}
export function DestinationStructure({type}:{type:"archive"|"lab"|"array"|"outpost"|"waypoint"|"field-log"}){if(type==="array")return <SignalArray/>;if(type==="outpost")return <ResearchOutpost/>;if(type==="archive")return <MissionArchive/>;if(type==="lab")return <SystemsLab/>;if(type==="waypoint")return <TrajectoryWaypoint/>;return <FieldLog/>}
