"use client";
import { useFrame } from "@react-three/fiber";
import { useMemo, useRef } from "react";
import * as THREE from "three";
import type { Group, Sprite } from "three";
import type { MarsDestination, MarsPosition } from "@/types/mars";
import { terrainHeight } from "./MarsTerrain";
import { DestinationStructure } from "./DestinationStructures";
import { MARS_VISUAL_SPEC as SPEC } from "./mars-visual-spec";

function DestinationLabel({destination,roverPosition}:{destination:MarsDestination;roverPosition:MarsPosition}){const group=useRef<Group>(null),sprite=useRef<Sprite>(null),lastDistance=useRef(-1);const labelY={array:11,archive:9,lab:7.2,outpost:5.2,"field-log":7,waypoint:8}[destination.structure];const texture=useMemo(()=>{const canvas=document.createElement("canvas");canvas.width=512;canvas.height=128;const map=new THREE.CanvasTexture(canvas);map.colorSpace=THREE.SRGBColorSpace;return map},[]);useFrame(({camera})=>{if(!group.current||!sprite.current)return;const cameraDistance=camera.position.distanceTo(group.current.getWorldPosition(new THREE.Vector3())),rounded=Math.round(Math.hypot(destination.position[0]-roverPosition[0],destination.position[2]-roverPosition[2])),material=sprite.current.material as THREE.SpriteMaterial;group.current.visible=cameraDistance<SPEC.labels.maxDistance;if(rounded!==lastDistance.current&&material.map){lastDistance.current=rounded;const canvas=material.map.image as HTMLCanvasElement,ctx=canvas.getContext("2d")!;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.font="28px monospace";ctx.fillStyle=SPEC.palette.textPrimary;ctx.fillText(destination.label,12,40);ctx.font="22px monospace";ctx.fillStyle=SPEC.palette.violetBright;ctx.fillText(`${rounded} m`,12,78);material.map.needsUpdate=true}const opacity=cameraDistance<=SPEC.labels.fadeStart?1:1-(cameraDistance-SPEC.labels.fadeStart)/(SPEC.labels.maxDistance-SPEC.labels.fadeStart);material.opacity=Math.max(0,opacity)});return <group ref={group} position={[0,labelY,0]}><mesh position={[0,-SPEC.labels.lineHeight/2,0]}><cylinderGeometry args={[.012,.012,SPEC.labels.lineHeight,4]}/><meshBasicMaterial color={SPEC.palette.violetDim} transparent opacity={.75}/></mesh><sprite ref={sprite} position={[1.8,.3,0]} scale={[5,1.25,1]}><spriteMaterial map={texture} transparent depthTest={false}/></sprite></group>}

export function DestinationMarker({destination,active,roverPosition,onAccess}:{destination:MarsDestination;active:boolean;roverPosition:MarsPosition;onAccess:(destination:MarsDestination)=>void}){const[x,,z]=destination.position;return <group position={[x,terrainHeight(x,z),z]} onClick={event=>{event.stopPropagation();onAccess(destination)}}><DestinationStructure type={destination.structure}/><DestinationLabel destination={destination} roverPosition={roverPosition}/>{active&&<mesh position={[0,.04,0]} rotation={[-Math.PI/2,0,0]}><ringGeometry args={[3.2,3.25,48]}/><meshBasicMaterial color={SPEC.palette.violet} transparent opacity={.55}/></mesh>}</group>}
