"use client";
import type { MarsDestination, RoverTelemetry } from "@/types/mars";
const headingLabel=(radians:number)=>["N","NE","E","SE","S","SW","W","NW"][Math.round((((radians%(Math.PI*2))+Math.PI*2)%(Math.PI*2))/(Math.PI/4))%8];
function MissionIdentity({fallback}:{fallback:boolean}){return <div className="hud-mission-identity"><span>MARS SURFACE {"//"} EXPLORATION MODE</span><strong>MA-01</strong><small>AUTONOMOUS EXPLORATION PLATFORM</small>{fallback&&<em>DIRECT SITE ACCESS</em>}</div>}
function MissionDirective(){return <div className="hud-directive"><span>MISSION DIRECTIVE</span><p>Explore the settlement to discover engineering work, projects, and ideas.</p></div>}
function Compass({degrees,heading}:{degrees:number;heading:string}){return <div className="hud-compass" aria-label={`Simulated heading ${heading}`}><i style={{transform:`rotate(${degrees}deg)`}}>↑</i><b>N</b><small>{heading} {"//"} {degrees.toString().padStart(3,"0")}°</small></div>}
function TelemetryPanel({telemetry,nearest}:{telemetry:RoverTelemetry;nearest:MarsDestination}){return <dl className="hud-telemetry"><div><dt>HEADING</dt><dd>{headingLabel(telemetry.heading)} {"//"} {Math.round(telemetry.heading*180/Math.PI+360)%360}°</dd></div><div><dt>ROVER STATE</dt><dd>{telemetry.speed>.05?"TRAVERSING":"STATIONARY"}</dd></div><div><dt>NEAREST SITE</dt><dd>{nearest.label}<br/>{Math.round(telemetry.distance)} U</dd></div></dl>}
function ControlStrip(){return <div className="hud-controls"><span><kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> DRIVE</span><span><kbd>E</kbd> INTERACT</span></div>}
export function MarsHUD({telemetry,nearest,destinations,onAccess,fallback=false}:{telemetry:RoverTelemetry;nearest:MarsDestination;destinations:MarsDestination[];onAccess:(site:MarsDestination)=>void;fallback?:boolean}){const degrees=Math.round((telemetry.heading*180/Math.PI+360)%360),heading=headingLabel(telemetry.heading);return <div className={`mars-hud ${fallback?"mars-hud-fallback":""}`}><MissionIdentity fallback={fallback}/>{!fallback&&<><MissionDirective/><Compass degrees={degrees} heading={heading}/><TelemetryPanel telemetry={telemetry} nearest={nearest}/><ControlStrip/></>}<details className="hud-directory"><summary>SITE DIRECTORY</summary><div>{destinations.map(site=><button key={site.id} onClick={()=>onAccess(site)}><span>{site.site}</span>{site.label}</button>)}</div></details></div>}
